### ISSUE TITLE
Add to KDE store

### ISSUE THREAD

**Issue by quazar-omega** [rose-pine/konsole#3]
Thanks for the amazing themes!
I was wondering why I couldn't find them from within Konsole, for easier installation, would you consider uploading the themes to the [store](https://store.kde.org/browse?cat=462&ord=latest) too?

**Comment by mvllow** [comment]
This would probably be best done by someone who uses this, as I would be unable to test. If anyone would like to publish this please let us know :)

**Comment by quazar-omega** [comment]
Sure, I will try myself and let you know!

**Comment by quazar-omega** [comment]
I'm going right now through the process of publishing, but I need to provide a license, can you please add that in so I can respect Pling's terms?  
I'd imagine it's just the MIT license yes?

**Comment by mvllow** [comment]
Added the MIT license :)

**Comment by quazar-omega** [comment]
Perfect thanks!  
Could you also add a release? Just for completeness I'd like to publish that link too.

Btw, you can currently check out the product [here](https://www.pling.com/p/2048823/), I'll try to see if it installs correctly

**Comment by mvllow** [comment]
Released 0.1.0 and added you as a maintainer if you ever want to make more releases in the future :)

As far as the listing, are you able to add the accent over the "e" in Rosé?

**Comment by quazar-omega** [comment]
Ah ok, that's neat!
> are you able to add the accent over the "e" in Rosé?

I tired, but unfortunately it doesn't get accepted, maybe I can put it in the description instead

**Comment by mvllow** [comment]
> I tired, but unfortunately it doesn't get accepted

No worries

**Comment by quazar-omega** [comment]
Now I'm splitting the product into more for each of the flavors, since it seems that it isn't possible to install more schemes from the same entry atm (which is kinda weird, but it is what it is I guess).  
I was wondering, is the svg of the Rosé Pine icon Dawn and Moon flavors available somewhere? I only found the [PNGs](https://github.com/rose-pine/rose-pine-site/tree/main/public/assets)

**Comment by quazar-omega** [comment]
Done!! 🎉🎉🎉
https://www.pling.com/member/722823/products/

I'll edit them with the correct icons (if you know where to find them, but I can also make them myself otherwise) and screenshots tomorrow, but it's already working fine, thank you again <3

**Comment by mvllow** [comment]
Hmm, let me know if this works: https://www.figma.com/file/puPTa927EZuE6N9SnF4vCV/Ros%C3%A9-Pine?type=design&t=QhQUNMv9PZzI2l6Q-6

**Comment by quazar-omega** [comment]
Sorry I couldn't get back to it earlier.  
I'm not really sure how to use Figma tbh, I'll just pick the appropriate colors and reproduce the icons in Inkscape, I'll post the resulting SVGs here if anyone ever needs those.  
What license are they under? I'll make sure to add any needed attribution

**Comment by quazar-omega** [comment]
Here they are:
<img alt="rosé-pine-dawn-icon" width="100px" src="https://github.com/rose-pine/konsole/assets/56311398/fe12eb46-848c-419d-9c35-fb142ac19223">
<img alt="rosé-pine-icon" width="100px" src="https://github.com/rose-pine/konsole/assets/56311398/24a39d5c-74ad-418f-b680-5ac9d1424dfb">
<img alt="rosé-pine-moon-icon" width="100px" src="https://github.com/rose-pine/konsole/assets/56311398/35bc66a8-90c8-4ba2-828b-7ad68635e79e)">

**Comment by quazar-omega** [comment]
Done with the rest of the additions too now!
<img alt="hulk-hogan-mic-drop" width="100px" src="https://github.com/rose-pine/konsole/assets/56311398/b4a1ede3-90e7-4d42-ab9e-0a365278af33">

**Comment by mvllow** [comment]
Not sure how to license artwork to be honest—no attribution is necessary :)

Thank you for working on this!

**Comment by quazar-omega** [comment]
If you're interested you can see [choosealicense](https://choosealicense.com/non-software/) to get an overview, you could say that the CC-BY-SA 4.0 is the GPL 3.0 of the artwork licenses, while CC-BY 4.0 is more like MIT I guess.  
Up to you if you want to add one.

> Thank you for working on this!

You got it! I was very happy to
